### ISSUE TITLE
Neflix BSP revision

### ISSUE THREAD

**Issue by ghost** [dev-harsh1998/android_device_realme_x2#4]
https://github.com/dev-harsh1998/android_device_realme_x2/blob/2770727f98c7e07e78052a6b691cf816ca818dfa/vendor_props.mk#L58

Stock rom use ro.netflix.bsp_rev=Q6150-17263-1 for RMX1991, RMX1992 and RMX1993 so why you defined it to this values (afaik, your values is only for sdm670, sdm710 and sdm712) ?

**Comment by dev-harsh1998** [comment]
@TheMalachite Please do a pull

**Comment by ghost** [comment]
@dev-harsh1998 here we go https://github.com/dev-harsh1998/android_device_realme_x2/pull/5
